import { useState, useCallback } from "react";

const INITIAL_CUPS = [
  {
    id: "cup1",
    label: "Cup 1 (Pizza)",
    idlePos: [-0.25, 0.60, 0.35],
    scatterPos: [-2.75, 1.15, 0.75],
    width: 1.73,
    height: 1.85,
    rotation: [0, 0, -0.06],
    opacity: 1,
    renderOrder: 0,
  },
  {
    id: "cup2",
    label: "Cup 2 (Pasta)",
    idlePos: [3.25, 0.65, -0.25],
    scatterPos: [2.50, 1.35, -0.50],
    width: 1.78,
    height: 1.82,
    rotation: [0, 0, -0.35],
    opacity: 1,
    renderOrder: 0,
  },
  {
    id: "cup3",
    label: "Cup 3 (Desserts)",
    idlePos: [-0.25, -1.20, 0.45],
    scatterPos: [-2.30, -1.30, 0.85],
    width: 1.76,
    height: 1.82,
    rotation: [0, 0, 0.08],
    opacity: 1,
    renderOrder: 0,
  },
  {
    id: "cup4",
    label: "Cup 4 (Drinks)",
    idlePos: [3.35, -1.20, 0.10],
    scatterPos: [2.45, -1.15, 0.35],
    width: 1.69,
    height: 1.70,
    rotation: [0, 0, -0.5],
    opacity: 1,
    renderOrder: 0,
  },
  {
    id: "cup5",
    label: "Cup 5 (Coffee — satellite)",
    idlePos: [0.44, -1.17, 0.00],
    scatterPos: [0.80, 2.00, 0.00],
    width: 3.28,
    height: 3.856,
    rotation: [0, 0, -0.15],
    opacity: 1,
    renderOrder: 0,
  },
  {
    id: "cup6",
    label: "Cup 6 (Bites)",
    idlePos: [1.50, 1.40, -0.10],
    scatterPos: [1.20, 2.50, -0.10],
    width: 1.80,
    height: 1.90,
    rotation: [0, 0, 0.10],
    opacity: 1,
    renderOrder: 0,
  },
];

const INITIAL_MAIN = {
  id: "main",
  label: "Main Cup (Coffee — hero)",
  idleY: -1.87,
  idleScale: 3.2,
  risenY: 0.50,
  risenScale: 3.55,
  meshOffsetX: 0.44,
  rotationZ: -0.15,
  width: null,  // derived from aspect
  height: 1.205,
};

// ── helpers ────────────────────────────────────────────────────────────────

function fmt(n) {
  return parseFloat(n.toFixed(4));
}

function Slider({ label, value, min, max, step = 0.01, onChange }) {
  return (
    <div style={{ marginBottom: 6 }}>
      <div style={{ display: "flex", justifyContent: "space-between", fontSize: 11, color: "#aaa", marginBottom: 2 }}>
        <span>{label}</span>
        <span style={{ color: "#e8d5b0", fontVariantNumeric: "tabular-nums" }}>{fmt(value)}</span>
      </div>
      <input
        type="range"
        min={min}
        max={max}
        step={step}
        value={value}
        onChange={(e) => onChange(parseFloat(e.target.value))}
        style={{ width: "100%", accentColor: "#c9a96e", cursor: "pointer" }}
      />
    </div>
  );
}

function NumberInput({ label, value, step = 0.01, onChange }) {
  return (
    <div style={{ marginBottom: 6 }}>
      <div style={{ fontSize: 11, color: "#aaa", marginBottom: 2 }}>{label}</div>
      <input
        type="number"
        value={fmt(value)}
        step={step}
        onChange={(e) => onChange(parseFloat(e.target.value) || 0)}
        style={{
          width: "100%",
          background: "#1a1a1a",
          border: "1px solid #333",
          borderRadius: 4,
          color: "#e8d5b0",
          padding: "4px 8px",
          fontSize: 12,
          boxSizing: "border-box",
        }}
      />
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div style={{ marginBottom: 16 }}>
      <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: "#666", marginBottom: 8 }}>{title}</div>
      {children}
    </div>
  );
}

// ── code generators ────────────────────────────────────────────────────────

function generateCupConfig(cups) {
  const entries = cups.map((c) => `  {
    id: '${c.id}',
    url: cup${c.id.replace("cup", "")}Url,
    idlePos:    [${c.idlePos.map(fmt).join(", ")}],
    scatterPos: [${c.scatterPos.map(fmt).join(", ")}],
    width: ${fmt(c.width)},
    height: ${fmt(c.height)},
    rotation: [${c.rotation[0]}, ${c.rotation[1]}, ${fmt(c.rotation[2])}],
    opacity: ${c.opacity},${c.id === "cup6" ? "\n    renderOrder: 0," : ""}
  }`).join(",\n");

  return `// cupConfig.js — generated by CupConfigEditor
// Paste this file over your existing cupConfig.js

import cup1Url from './models/satellites/cup1.png';
import cup2Url from './models/satellites/cup2.png';
import cup3Url from './models/satellites/cup3.png';
import cup4Url from './models/satellites/cup4.png';
import cup5Url from './models/satellites/cup5.png';
import cup6Url from './models/satellites/cup6.png';

export const CUP_CONFIGS = [
${entries}
];

export const CUP_CONFIG_BY_ID = Object.fromEntries(
  CUP_CONFIGS.map((c) => [c.id, c])
);

export const CATEGORY_TO_CUP = {
  coffee:   'cup5',
  pizza:    'cup1',
  pasta:    'cup2',
  desserts: 'cup3',
  drinks:   'cup4',
  bites:    'cup6',
};
`;
}

function generateMainCupPatch(main) {
  return `// MainCupImage.jsx — REPLACE ONLY these constants near the top of the file
// (everything else in MainCupImage.jsx stays the same)

const ROTATION    = [0, 0, ${fmt(main.rotationZ)}];

// Idle resting position
const IDLE_Y     = ${fmt(main.idleY)};
const IDLE_SCALE = ${fmt(main.idleScale)};

// Risen (fully scrolled) position
const RISEN_Y     = ${fmt(main.risenY)};
const RISEN_SCALE = ${fmt(main.risenScale)};

// Inside the return() — replace the <group> and <mesh> block:
// <group ref={groupRef} position={[0, IDLE_Y, 0]} scale={IDLE_SCALE}>
//   <mesh position={[${fmt(main.meshOffsetX)}, height / 2, 0]} rotation={ROTATION}>
//     <planeGeometry args={[width, height]} />   // height = ${fmt(main.height)}
`;
}

// ── main component ─────────────────────────────────────────────────────────

export default function CupConfigEditor() {
  const [cups, setCups] = useState(INITIAL_CUPS);
  const [main, setMain] = useState(INITIAL_MAIN);
  const [selected, setSelected] = useState("main");
  const [copied, setCopied] = useState(null);
  const [tab, setTab] = useState("cupConfig");

  const updateCup = useCallback((id, field, value) => {
    setCups((prev) => prev.map((c) => c.id === id ? { ...c, [field]: value } : c));
  }, []);

  const updateCupVec = useCallback((id, field, axis, value) => {
    setCups((prev) =>
      prev.map((c) => {
        if (c.id !== id) return c;
        const arr = [...c[field]];
        arr[axis] = value;
        return { ...c, [field]: arr };
      })
    );
  }, []);

  const updateMain = useCallback((field, value) => {
    setMain((prev) => ({ ...prev, [field]: value }));
  }, []);

  const copy = (text, key) => {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(key);
      setTimeout(() => setCopied(null), 2000);
    });
  };

  const reset = () => {
    if (selected === "main") setMain(INITIAL_MAIN);
    else setCups((prev) => prev.map((c) => c.id === selected ? INITIAL_CUPS.find((x) => x.id === selected) : c));
  };

  const selectedCup = selected !== "main" ? cups.find((c) => c.id === selected) : null;

  const cupConfigCode = generateCupConfig(cups);
  const mainPatchCode = generateMainCupPatch(main);

  return (
    <div style={{
      display: "flex",
      height: "100vh",
      background: "#0d0d0d",
      color: "#e0d6c8",
      fontFamily: "'Inter', system-ui, sans-serif",
      fontSize: 13,
      overflow: "hidden",
    }}>
      {/* ── left: cup selector ── */}
      <div style={{
        width: 180,
        borderRight: "1px solid #222",
        display: "flex",
        flexDirection: "column",
        overflowY: "auto",
        padding: "16px 0",
        gap: 2,
        flexShrink: 0,
      }}>
        <div style={{ padding: "0 16px 12px", fontSize: 10, fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: "#555" }}>Cups</div>
        {[{ id: "main", label: "Main Cup (Hero)" }, ...INITIAL_CUPS].map((c) => (
          <button
            key={c.id}
            onClick={() => setSelected(c.id)}
            style={{
              textAlign: "left",
              padding: "8px 16px",
              background: selected === c.id ? "#1e1a14" : "transparent",
              border: "none",
              borderLeft: `3px solid ${selected === c.id ? "#c9a96e" : "transparent"}`,
              color: selected === c.id ? "#e8d5b0" : "#888",
              cursor: "pointer",
              fontSize: 12,
              transition: "all 0.15s",
            }}
          >
            {c.label || c.id}
          </button>
        ))}
      </div>

      {/* ── center: controls ── */}
      <div style={{
        width: 280,
        borderRight: "1px solid #222",
        overflowY: "auto",
        padding: 20,
        flexShrink: 0,
      }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }}>
          <div style={{ fontWeight: 600, color: "#e8d5b0" }}>
            {selected === "main" ? "Main Cup (Hero)" : cups.find((c) => c.id === selected)?.label}
          </div>
          <button onClick={reset} style={{
            background: "#1a1a1a", border: "1px solid #333", borderRadius: 4,
            color: "#888", fontSize: 11, padding: "4px 10px", cursor: "pointer",
          }}>Reset</button>
        </div>

        {selected === "main" ? (
          <>
            <Section title="Idle (resting)">
              <Slider label="Idle Y" value={main.idleY} min={-4} max={2} step={0.01} onChange={(v) => updateMain("idleY", v)} />
              <Slider label="Idle Scale" value={main.idleScale} min={1} max={6} step={0.05} onChange={(v) => updateMain("idleScale", v)} />
            </Section>
            <Section title="Risen (scrolled)">
              <Slider label="Risen Y" value={main.risenY} min={-2} max={4} step={0.01} onChange={(v) => updateMain("risenY", v)} />
              <Slider label="Risen Scale" value={main.risenScale} min={1} max={6} step={0.05} onChange={(v) => updateMain("risenScale", v)} />
            </Section>
            <Section title="Mesh">
              <Slider label="Mesh Offset X" value={main.meshOffsetX} min={-2} max={2} step={0.01} onChange={(v) => updateMain("meshOffsetX", v)} />
              <Slider label="Rotation Z (rad)" value={main.rotationZ} min={-Math.PI} max={Math.PI} step={0.01} onChange={(v) => updateMain("rotationZ", v)} />
              <Slider label="Plane Height" value={main.height} min={0.2} max={4} step={0.01} onChange={(v) => updateMain("height", v)} />
            </Section>
          </>
        ) : selectedCup ? (
          <>
            <Section title="Idle Position">
              <Slider label="Idle X" value={selectedCup.idlePos[0]} min={-5} max={5} step={0.01} onChange={(v) => updateCupVec(selectedCup.id, "idlePos", 0, v)} />
              <Slider label="Idle Y" value={selectedCup.idlePos[1]} min={-4} max={4} step={0.01} onChange={(v) => updateCupVec(selectedCup.id, "idlePos", 1, v)} />
              <Slider label="Idle Z" value={selectedCup.idlePos[2]} min={-3} max={3} step={0.01} onChange={(v) => updateCupVec(selectedCup.id, "idlePos", 2, v)} />
            </Section>
            <Section title="Scatter Position">
              <Slider label="Scatter X" value={selectedCup.scatterPos[0]} min={-5} max={5} step={0.01} onChange={(v) => updateCupVec(selectedCup.id, "scatterPos", 0, v)} />
              <Slider label="Scatter Y" value={selectedCup.scatterPos[1]} min={-4} max={4} step={0.01} onChange={(v) => updateCupVec(selectedCup.id, "scatterPos", 1, v)} />
              <Slider label="Scatter Z" value={selectedCup.scatterPos[2]} min={-3} max={3} step={0.01} onChange={(v) => updateCupVec(selectedCup.id, "scatterPos", 2, v)} />
            </Section>
            <Section title="Dimensions">
              <Slider label="Width" value={selectedCup.width} min={0.5} max={5} step={0.01} onChange={(v) => updateCup(selectedCup.id, "width", v)} />
              <Slider label="Height" value={selectedCup.height} min={0.5} max={5} step={0.01} onChange={(v) => updateCup(selectedCup.id, "height", v)} />
            </Section>
            <Section title="Rotation (radians)">
              <Slider label="Rotation X" value={selectedCup.rotation[0]} min={-Math.PI} max={Math.PI} step={0.01} onChange={(v) => updateCupVec(selectedCup.id, "rotation", 0, v)} />
              <Slider label="Rotation Y" value={selectedCup.rotation[1]} min={-Math.PI} max={Math.PI} step={0.01} onChange={(v) => updateCupVec(selectedCup.id, "rotation", 1, v)} />
              <Slider label="Rotation Z" value={selectedCup.rotation[2]} min={-Math.PI} max={Math.PI} step={0.01} onChange={(v) => updateCupVec(selectedCup.id, "rotation", 2, v)} />
            </Section>
            <Section title="Other">
              <Slider label="Opacity" value={selectedCup.opacity} min={0} max={1} step={0.01} onChange={(v) => updateCup(selectedCup.id, "opacity", v)} />
            </Section>
          </>
        ) : null}
      </div>

      {/* ── right: code output ── */}
      <div style={{ flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" }}>
        {/* tab bar */}
        <div style={{ display: "flex", borderBottom: "1px solid #222", padding: "0 20px", gap: 4, paddingTop: 12 }}>
          {[["cupConfig", "cupConfig.js"], ["mainPatch", "MainCupImage.jsx patch"]].map(([key, label]) => (
            <button
              key={key}
              onClick={() => setTab(key)}
              style={{
                background: tab === key ? "#1a1710" : "transparent",
                border: "1px solid " + (tab === key ? "#c9a96e" : "#333"),
                borderBottom: tab === key ? "1px solid #1a1710" : "1px solid #222",
                borderRadius: "4px 4px 0 0",
                color: tab === key ? "#e8d5b0" : "#666",
                padding: "6px 14px",
                fontSize: 12,
                cursor: "pointer",
                marginBottom: -1,
              }}
            >{label}</button>
          ))}
          <div style={{ flex: 1 }} />
          <button
            onClick={() => copy(tab === "cupConfig" ? cupConfigCode : mainPatchCode, tab)}
            style={{
              background: copied === tab ? "#2a4a2a" : "#1a1a1a",
              border: "1px solid " + (copied === tab ? "#4a9a4a" : "#444"),
              borderRadius: 4,
              color: copied === tab ? "#6fce6f" : "#aaa",
              padding: "6px 14px",
              fontSize: 12,
              cursor: "pointer",
              marginBottom: 8,
              transition: "all 0.2s",
            }}
          >{copied === tab ? "✓ Copied!" : "Copy"}</button>
        </div>

        {/* code block */}
        <div style={{ flex: 1, overflowY: "auto", padding: 20 }}>
          <pre style={{
            margin: 0,
            fontFamily: "'JetBrains Mono', 'Fira Code', 'Consolas', monospace",
            fontSize: 11.5,
            lineHeight: 1.6,
            color: "#c9d8b0",
            whiteSpace: "pre-wrap",
            wordBreak: "break-word",
          }}>
            {tab === "cupConfig" ? cupConfigCode : mainPatchCode}
          </pre>
        </div>

        {/* bottom hint */}
        <div style={{ borderTop: "1px solid #1a1a1a", padding: "10px 20px", fontSize: 11, color: "#444" }}>
          Adjust sliders → code updates live → Copy and paste into your project
        </div>
      </div>
    </div>
  );
}